### ISSUE TITLE
Decompose Magento "entity" data loading process

### ISSUE THREAD

**Issue by Borales** [deity-io/falcon#140]
In order to follow Magento's data loading flow - we need to get rid of custom hooks in Deity/Magento module, which forces us to use native Magento REST API endpoints to fetch the data.

- [ ] investigate which parts could be decomposed
  - [ ] product `breadcrumbs` data (https://github.com/deity-io/falcon-magento2-development/issues/19)
  - [ ] category/product URL is being handled by Magento (https://github.com/deity-io/falcon-magento2-development/issues/18)
  - [ ] use canonical URL data (https://github.com/deity-io/falcon-magento2-development/issues/2)
- [ ] ensure resolvers load related data correctly
- [ ] provide caching mechanism to manage the data and reduce the amount of requests

---

Related to #118 

@sergy-gzh
