### ISSUE TITLE
Payments

### ISSUE THREAD

**Issue by Borales** [deity-io/falcon#233]
Introduce support for external Payment systems

- [ ] support multi-api payments
- [ ] support callback hooks (endpoints)
- [ ] tests and docs
