### ISSUE TITLE
[Discussion] ServiceWorker improvements

### ISSUE THREAD

**Issue by Borales** [deity-io/falcon#419]
### What should be changed/improved?

The current behavior of ServiceWorker within Falcon-Client context could be improved. 
With the latest version of Workbox package (latest - `4.3.0`, we use - `3.5.0`) - workbox does not allow us to call `workbox.skipWaiting()` method anymore (like we did in https://latest.snapshot.deity.io/sw.js), which forces browsers to update it immediately (applying the latest serviceWorker instance).

[ServiceWorker lifecycle](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle) discourages such behavior:

> - Allow a new service worker to get itself ready without disrupting the current one.
> - Ensure an in-scope page is controlled by the same service worker (or no service worker) throughout.
> - Ensure there's only one version of your site running at once.
> 
> That last one is pretty important. Without service workers, users can load one tab to your site, then later open another. This can result in two versions of your site running at the same time. Sometimes this is ok, but if you're dealing with storage you can easily end up with two tabs having very different opinions on how their shared storage should be managed. This can result in errors, or worse, data loss.

The current behavior could potentially harm user-experience for the visitors, and therefore decrease the shop revenue.

### Your suggested solution

- Falcon-Client's implementation of ServiceWorker generation should not be forcing browsers to apply ServiceWorker immediately (through `skipWaiting`), but rather follow the proper ServiceWorker lifecycle
- ServiceWorker must be able to precache our bundle files correctly, and to make it possible - we need to get rid of "hash" suffix in bundle filenames (`/static/js/client.0f3ef189.js` must be `/static/js/client.js`, so workbox itself would calculate the revision automatically). This way - ServiceWorker will be able to calculate the correct "diff" for the precached files by matching filenames from `sw.js` and "Cache storage" items (so deploying new version - won't break the UI by providing new bundle files)
- Allow developers to define their own custom SW template (for example `client/src/sw.js`) so Falcon-Client could check it or apply the built-in one.

### Things to check/investigate

- Server-Side Rendering while keeping the "previous" ServiceWorker and precached bundle files

### TODO

- [x] Update Workbox package to the [latest version](https://github.com/GoogleChrome/workbox/releases)
- [x] Remove hashes from bundle filenames
- [x] Allow developers to define their own SW template

---

This is a "ticket" to discuss this improvement openly to get opinions from different perspectives.

CC: @mateuszwozniak @tutok @cane-lagerwaard 

---

### Update (17/04/2019)

Turned out `skipWaiting` method is still [available](https://developers.google.com/web/tools/workbox/modules/workbox-core#skip_waiting_and_clients_claim), but via `workbox.core.skipWaiting()` (not `workbox.skipWaiting()`).

They also mention some possible risks [here](https://stackoverflow.com/questions/51715127/what-are-the-downsides-to-using-skipwaiting-and-clientsclaim-with-workbox).

**Comment by tutok** [comment]
Being strict, it looks like `falcon-client` (because of `SSR`) and `falcon-server` with its backend (because of data for `SSR` and web browser) needs to know which version of the application is requesting.
So each request for both static files and graphQL data needs to send info about current ServiceWorker version, to give a chance to `falcon` to prepare a response for corresponding request version.

But, let's consider a request for `/` done by WebBrowser with  SerwiceWorker in `v1.0` while version `v1.1` is available at the same time. I think there is no point to wait infinitely with the update. I think we could force a full page reload and use `skipWiting`, so the latest version of the web page will be rendered and ServiceWorker could be updated.

Actually, it is hard for me to imagine a situation when we **need** to wait with updating Service Worker **except for** the requests which will change the data on the server (`POST`, `DELETE`, `PUT`, `PATCH`). As these request could contain data shaped in `v1.0` so we need to process that requests as if `v1.1` would not be available - preventing possible data loss. But as soon as WebBrowser with ServiceWorker in `v1.0` will do any `GET` request, and version will differentiate we should be able to force a full page reload with `skipWaiting`

**Comment by tutok** [comment]
after reading the following:
* https://stackoverflow.com/questions/51715127/what-are-the-downsides-to-using-skipwaiting-and-clientsclaim-with-workbox
* https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v3
* https://developers.google.com/web/tools/workbox/modules/workbox-precaching#explanation_of_the_precache_list

I can not find any reason to do: 
>  - [ ] Remove hashes from bundle filenames

**Comment by Borales** [comment]
After discussing "Remove hashes from bundle filenames" section in person - this item can be considered as irrelevant (due to "app-shell" cache).
